//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteAdminSide.InstituteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EmpPayAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EmpPayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpPayMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpPayYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpAddress {
            get {
                return this.EmpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpAddressField, value) != true)) {
                    this.EmpAddressField = value;
                    this.RaisePropertyChanged("EmpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpContact {
            get {
                return this.EmpContactField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpContactField, value) != true)) {
                    this.EmpContactField = value;
                    this.RaisePropertyChanged("EmpContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpFName {
            get {
                return this.EmpFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpFNameField, value) != true)) {
                    this.EmpFNameField = value;
                    this.RaisePropertyChanged("EmpFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpLName {
            get {
                return this.EmpLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpLNameField, value) != true)) {
                    this.EmpLNameField = value;
                    this.RaisePropertyChanged("EmpLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpNIC {
            get {
                return this.EmpNICField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNICField, value) != true)) {
                    this.EmpNICField = value;
                    this.RaisePropertyChanged("EmpNIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EmpPayAmount {
            get {
                return this.EmpPayAmountField;
            }
            set {
                if ((this.EmpPayAmountField.Equals(value) != true)) {
                    this.EmpPayAmountField = value;
                    this.RaisePropertyChanged("EmpPayAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EmpPayDate {
            get {
                return this.EmpPayDateField;
            }
            set {
                if ((this.EmpPayDateField.Equals(value) != true)) {
                    this.EmpPayDateField = value;
                    this.RaisePropertyChanged("EmpPayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpPayMonth {
            get {
                return this.EmpPayMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpPayMonthField, value) != true)) {
                    this.EmpPayMonthField = value;
                    this.RaisePropertyChanged("EmpPayMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpPayYear {
            get {
                return this.EmpPayYearField;
            }
            set {
                if ((this.EmpPayYearField.Equals(value) != true)) {
                    this.EmpPayYearField = value;
                    this.RaisePropertyChanged("EmpPayYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [System.SerializableAttribute()]
    public partial class Teacher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherNICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TeacherPayAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherPayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherPayMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherPayYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherSubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherAddress {
            get {
                return this.TeacherAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherAddressField, value) != true)) {
                    this.TeacherAddressField = value;
                    this.RaisePropertyChanged("TeacherAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherContact {
            get {
                return this.TeacherContactField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherContactField, value) != true)) {
                    this.TeacherContactField = value;
                    this.RaisePropertyChanged("TeacherContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherFName {
            get {
                return this.TeacherFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherFNameField, value) != true)) {
                    this.TeacherFNameField = value;
                    this.RaisePropertyChanged("TeacherFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherLName {
            get {
                return this.TeacherLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherLNameField, value) != true)) {
                    this.TeacherLNameField = value;
                    this.RaisePropertyChanged("TeacherLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherMail {
            get {
                return this.TeacherMailField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherMailField, value) != true)) {
                    this.TeacherMailField = value;
                    this.RaisePropertyChanged("TeacherMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherNIC {
            get {
                return this.TeacherNICField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherNICField, value) != true)) {
                    this.TeacherNICField = value;
                    this.RaisePropertyChanged("TeacherNIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TeacherPayAmount {
            get {
                return this.TeacherPayAmountField;
            }
            set {
                if ((this.TeacherPayAmountField.Equals(value) != true)) {
                    this.TeacherPayAmountField = value;
                    this.RaisePropertyChanged("TeacherPayAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherPayDate {
            get {
                return this.TeacherPayDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherPayDateField, value) != true)) {
                    this.TeacherPayDateField = value;
                    this.RaisePropertyChanged("TeacherPayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherPayMonth {
            get {
                return this.TeacherPayMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherPayMonthField, value) != true)) {
                    this.TeacherPayMonthField = value;
                    this.RaisePropertyChanged("TeacherPayMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherPayYear {
            get {
                return this.TeacherPayYearField;
            }
            set {
                if ((this.TeacherPayYearField.Equals(value) != true)) {
                    this.TeacherPayYearField = value;
                    this.RaisePropertyChanged("TeacherPayYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherSubject {
            get {
                return this.TeacherSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherSubjectField, value) != true)) {
                    this.TeacherSubjectField = value;
                    this.RaisePropertyChanged("TeacherSubject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstituteService.IInstituteServices")]
    public interface IInstituteServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstituteServices/DoWork", ReplyAction="http://tempuri.org/IInstituteServices/DoWorkResponse")]
        void DoWork();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInstituteServicesChannel : InstituteAdminSide.InstituteService.IInstituteServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InstituteServicesClient : System.ServiceModel.ClientBase<InstituteAdminSide.InstituteService.IInstituteServices>, InstituteAdminSide.InstituteService.IInstituteServices {
        
        public InstituteServicesClient() {
        }
        
        public InstituteServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InstituteServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstituteServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstituteServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstituteService.IEmployeeServices")]
    public interface IEmployeeServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/SaveEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/SaveEmployeeResponse")]
        int SaveEmployee(InstituteAdminSide.InstituteService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/SearchEmployeeData", ReplyAction="http://tempuri.org/IEmployeeServices/SearchEmployeeDataResponse")]
        InstituteAdminSide.InstituteService.Employee SearchEmployeeData(int employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/UpdateEmployeeResponse")]
        int UpdateEmployee(InstituteAdminSide.InstituteService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/SaveEmployeePayments", ReplyAction="http://tempuri.org/IEmployeeServices/SaveEmployeePaymentsResponse")]
        int SaveEmployeePayments(InstituteAdminSide.InstituteService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetEmployeeData", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeeDataResponse")]
        System.Data.DataTable GetEmployeeData();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServicesChannel : InstituteAdminSide.InstituteService.IEmployeeServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServicesClient : System.ServiceModel.ClientBase<InstituteAdminSide.InstituteService.IEmployeeServices>, InstituteAdminSide.InstituteService.IEmployeeServices {
        
        public EmployeeServicesClient() {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveEmployee(InstituteAdminSide.InstituteService.Employee employee) {
            return base.Channel.SaveEmployee(employee);
        }
        
        public InstituteAdminSide.InstituteService.Employee SearchEmployeeData(int employeeid) {
            return base.Channel.SearchEmployeeData(employeeid);
        }
        
        public int UpdateEmployee(InstituteAdminSide.InstituteService.Employee employee) {
            return base.Channel.UpdateEmployee(employee);
        }
        
        public int SaveEmployeePayments(InstituteAdminSide.InstituteService.Employee employee) {
            return base.Channel.SaveEmployeePayments(employee);
        }
        
        public System.Data.DataTable GetEmployeeData() {
            return base.Channel.GetEmployeeData();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstituteService.ITeacherServices")]
    public interface ITeacherServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/SaveTeacher", ReplyAction="http://tempuri.org/ITeacherServices/SaveTeacherResponse")]
        int SaveTeacher(InstituteAdminSide.InstituteService.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/SearchTeacherData", ReplyAction="http://tempuri.org/ITeacherServices/SearchTeacherDataResponse")]
        InstituteAdminSide.InstituteService.Teacher SearchTeacherData(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/UpdateTeacher", ReplyAction="http://tempuri.org/ITeacherServices/UpdateTeacherResponse")]
        int UpdateTeacher(InstituteAdminSide.InstituteService.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/SaveTeacherPayment", ReplyAction="http://tempuri.org/ITeacherServices/SaveTeacherPaymentResponse")]
        int SaveTeacherPayment(InstituteAdminSide.InstituteService.Teacher teacher);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeacherServicesChannel : InstituteAdminSide.InstituteService.ITeacherServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeacherServicesClient : System.ServiceModel.ClientBase<InstituteAdminSide.InstituteService.ITeacherServices>, InstituteAdminSide.InstituteService.ITeacherServices {
        
        public TeacherServicesClient() {
        }
        
        public TeacherServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeacherServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveTeacher(InstituteAdminSide.InstituteService.Teacher teacher) {
            return base.Channel.SaveTeacher(teacher);
        }
        
        public InstituteAdminSide.InstituteService.Teacher SearchTeacherData(int teacherId) {
            return base.Channel.SearchTeacherData(teacherId);
        }
        
        public int UpdateTeacher(InstituteAdminSide.InstituteService.Teacher teacher) {
            return base.Channel.UpdateTeacher(teacher);
        }
        
        public int SaveTeacherPayment(InstituteAdminSide.InstituteService.Teacher teacher) {
            return base.Channel.SaveTeacherPayment(teacher);
        }
    }
}
