//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteAdminSide.InstituteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EmpPayAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EmpPayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpPayMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpPayYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpAddress {
            get {
                return this.EmpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpAddressField, value) != true)) {
                    this.EmpAddressField = value;
                    this.RaisePropertyChanged("EmpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpContact {
            get {
                return this.EmpContactField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpContactField, value) != true)) {
                    this.EmpContactField = value;
                    this.RaisePropertyChanged("EmpContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpFName {
            get {
                return this.EmpFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpFNameField, value) != true)) {
                    this.EmpFNameField = value;
                    this.RaisePropertyChanged("EmpFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpLName {
            get {
                return this.EmpLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpLNameField, value) != true)) {
                    this.EmpLNameField = value;
                    this.RaisePropertyChanged("EmpLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpNIC {
            get {
                return this.EmpNICField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNICField, value) != true)) {
                    this.EmpNICField = value;
                    this.RaisePropertyChanged("EmpNIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EmpPayAmount {
            get {
                return this.EmpPayAmountField;
            }
            set {
                if ((this.EmpPayAmountField.Equals(value) != true)) {
                    this.EmpPayAmountField = value;
                    this.RaisePropertyChanged("EmpPayAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EmpPayDate {
            get {
                return this.EmpPayDateField;
            }
            set {
                if ((this.EmpPayDateField.Equals(value) != true)) {
                    this.EmpPayDateField = value;
                    this.RaisePropertyChanged("EmpPayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpPayMonth {
            get {
                return this.EmpPayMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpPayMonthField, value) != true)) {
                    this.EmpPayMonthField = value;
                    this.RaisePropertyChanged("EmpPayMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpPayYear {
            get {
                return this.EmpPayYearField;
            }
            set {
                if ((this.EmpPayYearField.Equals(value) != true)) {
                    this.EmpPayYearField = value;
                    this.RaisePropertyChanged("EmpPayYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [System.SerializableAttribute()]
    public partial class Teacher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherNICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TeacherPayAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherPayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherPayMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherPayYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherSubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherAddress {
            get {
                return this.TeacherAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherAddressField, value) != true)) {
                    this.TeacherAddressField = value;
                    this.RaisePropertyChanged("TeacherAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherContact {
            get {
                return this.TeacherContactField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherContactField, value) != true)) {
                    this.TeacherContactField = value;
                    this.RaisePropertyChanged("TeacherContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherFName {
            get {
                return this.TeacherFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherFNameField, value) != true)) {
                    this.TeacherFNameField = value;
                    this.RaisePropertyChanged("TeacherFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherLName {
            get {
                return this.TeacherLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherLNameField, value) != true)) {
                    this.TeacherLNameField = value;
                    this.RaisePropertyChanged("TeacherLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherMail {
            get {
                return this.TeacherMailField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherMailField, value) != true)) {
                    this.TeacherMailField = value;
                    this.RaisePropertyChanged("TeacherMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherNIC {
            get {
                return this.TeacherNICField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherNICField, value) != true)) {
                    this.TeacherNICField = value;
                    this.RaisePropertyChanged("TeacherNIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TeacherPayAmount {
            get {
                return this.TeacherPayAmountField;
            }
            set {
                if ((this.TeacherPayAmountField.Equals(value) != true)) {
                    this.TeacherPayAmountField = value;
                    this.RaisePropertyChanged("TeacherPayAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherPayDate {
            get {
                return this.TeacherPayDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherPayDateField, value) != true)) {
                    this.TeacherPayDateField = value;
                    this.RaisePropertyChanged("TeacherPayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherPayMonth {
            get {
                return this.TeacherPayMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherPayMonthField, value) != true)) {
                    this.TeacherPayMonthField = value;
                    this.RaisePropertyChanged("TeacherPayMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherPayYear {
            get {
                return this.TeacherPayYearField;
            }
            set {
                if ((this.TeacherPayYearField.Equals(value) != true)) {
                    this.TeacherPayYearField = value;
                    this.RaisePropertyChanged("TeacherPayYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherSubject {
            get {
                return this.TeacherSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherSubjectField, value) != true)) {
                    this.TeacherSubjectField = value;
                    this.RaisePropertyChanged("TeacherSubject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseBatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseStartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseTeacherIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseBatch {
            get {
                return this.CourseBatchField;
            }
            set {
                if ((this.CourseBatchField.Equals(value) != true)) {
                    this.CourseBatchField = value;
                    this.RaisePropertyChanged("CourseBatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseDay {
            get {
                return this.CourseDayField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseDayField, value) != true)) {
                    this.CourseDayField = value;
                    this.RaisePropertyChanged("CourseDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseEndTime {
            get {
                return this.CourseEndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseEndTimeField, value) != true)) {
                    this.CourseEndTimeField = value;
                    this.RaisePropertyChanged("CourseEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseStartTime {
            get {
                return this.CourseStartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseStartTimeField, value) != true)) {
                    this.CourseStartTimeField = value;
                    this.RaisePropertyChanged("CourseStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseTeacherId {
            get {
                return this.CourseTeacherIdField;
            }
            set {
                if ((this.CourseTeacherIdField.Equals(value) != true)) {
                    this.CourseTeacherIdField = value;
                    this.RaisePropertyChanged("CourseTeacherId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentPayMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentPayYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Drawing.Image getImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stuAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stuContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stuCourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stuFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stuGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stuLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stuPhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentPayMonth {
            get {
                return this.StudentPayMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentPayMonthField, value) != true)) {
                    this.StudentPayMonthField = value;
                    this.RaisePropertyChanged("StudentPayMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentPayYear {
            get {
                return this.StudentPayYearField;
            }
            set {
                if ((this.StudentPayYearField.Equals(value) != true)) {
                    this.StudentPayYearField = value;
                    this.RaisePropertyChanged("StudentPayYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Image getImg {
            get {
                return this.getImgField;
            }
            set {
                if ((object.ReferenceEquals(this.getImgField, value) != true)) {
                    this.getImgField = value;
                    this.RaisePropertyChanged("getImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stuAddr {
            get {
                return this.stuAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.stuAddrField, value) != true)) {
                    this.stuAddrField = value;
                    this.RaisePropertyChanged("stuAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stuContact {
            get {
                return this.stuContactField;
            }
            set {
                if ((this.stuContactField.Equals(value) != true)) {
                    this.stuContactField = value;
                    this.RaisePropertyChanged("stuContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stuCourseID {
            get {
                return this.stuCourseIDField;
            }
            set {
                if ((this.stuCourseIDField.Equals(value) != true)) {
                    this.stuCourseIDField = value;
                    this.RaisePropertyChanged("stuCourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stuFName {
            get {
                return this.stuFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.stuFNameField, value) != true)) {
                    this.stuFNameField = value;
                    this.RaisePropertyChanged("stuFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stuGender {
            get {
                return this.stuGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.stuGenderField, value) != true)) {
                    this.stuGenderField = value;
                    this.RaisePropertyChanged("stuGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stuLName {
            get {
                return this.stuLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.stuLNameField, value) != true)) {
                    this.stuLNameField = value;
                    this.RaisePropertyChanged("stuLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stuPhoto {
            get {
                return this.stuPhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.stuPhotoField, value) != true)) {
                    this.stuPhotoField = value;
                    this.RaisePropertyChanged("stuPhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stuid {
            get {
                return this.stuidField;
            }
            set {
                if ((this.stuidField.Equals(value) != true)) {
                    this.stuidField = value;
                    this.RaisePropertyChanged("stuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstituteService.IInstituteServices")]
    public interface IInstituteServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstituteServices/DoWork", ReplyAction="http://tempuri.org/IInstituteServices/DoWorkResponse")]
        void DoWork();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInstituteServicesChannel : InstituteAdminSide.InstituteService.IInstituteServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InstituteServicesClient : System.ServiceModel.ClientBase<InstituteAdminSide.InstituteService.IInstituteServices>, InstituteAdminSide.InstituteService.IInstituteServices {
        
        public InstituteServicesClient() {
        }
        
        public InstituteServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InstituteServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstituteServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstituteServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstituteService.IEmployeeServices")]
    public interface IEmployeeServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/SaveEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/SaveEmployeeResponse")]
        int SaveEmployee(InstituteAdminSide.InstituteService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/SearchEmployeeData", ReplyAction="http://tempuri.org/IEmployeeServices/SearchEmployeeDataResponse")]
        InstituteAdminSide.InstituteService.Employee SearchEmployeeData(int employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/UpdateEmployeeResponse")]
        int UpdateEmployee(InstituteAdminSide.InstituteService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/SaveEmployeePayments", ReplyAction="http://tempuri.org/IEmployeeServices/SaveEmployeePaymentsResponse")]
        int SaveEmployeePayments(InstituteAdminSide.InstituteService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetEmployeeData", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeeDataResponse")]
        System.Data.DataSet GetEmployeeData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetEmployeePaymentFull", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeePaymentFullResponse")]
        System.Data.DataSet GetEmployeePaymentFull();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetEmployeePayment", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeePaymentResponse")]
        System.Data.DataSet GetEmployeePayment(InstituteAdminSide.InstituteService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetEmployeeLastId", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeeLastIdResponse")]
        int GetEmployeeLastId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetEmployeeAllPaymentReport", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeeAllPaymentReportResponse")]
        System.Data.DataSet GetEmployeeAllPaymentReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/GetEmployeeMonthYearpaymentReport", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeeMonthYearpaymentReportResponse")]
        System.Data.DataSet GetEmployeeMonthYearpaymentReport(InstituteAdminSide.InstituteService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeServices/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/DeleteEmployeeResponse")]
        int DeleteEmployee(int employeeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServicesChannel : InstituteAdminSide.InstituteService.IEmployeeServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServicesClient : System.ServiceModel.ClientBase<InstituteAdminSide.InstituteService.IEmployeeServices>, InstituteAdminSide.InstituteService.IEmployeeServices {
        
        public EmployeeServicesClient() {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveEmployee(InstituteAdminSide.InstituteService.Employee employee) {
            return base.Channel.SaveEmployee(employee);
        }
        
        public InstituteAdminSide.InstituteService.Employee SearchEmployeeData(int employeeid) {
            return base.Channel.SearchEmployeeData(employeeid);
        }
        
        public int UpdateEmployee(InstituteAdminSide.InstituteService.Employee employee) {
            return base.Channel.UpdateEmployee(employee);
        }
        
        public int SaveEmployeePayments(InstituteAdminSide.InstituteService.Employee employee) {
            return base.Channel.SaveEmployeePayments(employee);
        }
        
        public System.Data.DataSet GetEmployeeData() {
            return base.Channel.GetEmployeeData();
        }
        
        public System.Data.DataSet GetEmployeePaymentFull() {
            return base.Channel.GetEmployeePaymentFull();
        }
        
        public System.Data.DataSet GetEmployeePayment(InstituteAdminSide.InstituteService.Employee employee) {
            return base.Channel.GetEmployeePayment(employee);
        }
        
        public int GetEmployeeLastId() {
            return base.Channel.GetEmployeeLastId();
        }
        
        public System.Data.DataSet GetEmployeeAllPaymentReport() {
            return base.Channel.GetEmployeeAllPaymentReport();
        }
        
        public System.Data.DataSet GetEmployeeMonthYearpaymentReport(InstituteAdminSide.InstituteService.Employee employee) {
            return base.Channel.GetEmployeeMonthYearpaymentReport(employee);
        }
        
        public int DeleteEmployee(int employeeId) {
            return base.Channel.DeleteEmployee(employeeId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstituteService.ITeacherServices")]
    public interface ITeacherServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/SaveTeacher", ReplyAction="http://tempuri.org/ITeacherServices/SaveTeacherResponse")]
        int SaveTeacher(InstituteAdminSide.InstituteService.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/SearchTeacherData", ReplyAction="http://tempuri.org/ITeacherServices/SearchTeacherDataResponse")]
        InstituteAdminSide.InstituteService.Teacher SearchTeacherData(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/UpdateTeacher", ReplyAction="http://tempuri.org/ITeacherServices/UpdateTeacherResponse")]
        int UpdateTeacher(InstituteAdminSide.InstituteService.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/SaveTeacherPayment", ReplyAction="http://tempuri.org/ITeacherServices/SaveTeacherPaymentResponse")]
        int SaveTeacherPayment(InstituteAdminSide.InstituteService.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/GetTeacherData", ReplyAction="http://tempuri.org/ITeacherServices/GetTeacherDataResponse")]
        System.Data.DataSet GetTeacherData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/GetTeachersIncome", ReplyAction="http://tempuri.org/ITeacherServices/GetTeachersIncomeResponse")]
        System.Data.DataSet GetTeachersIncome(InstituteAdminSide.InstituteService.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/GetTeachersPaymentFull", ReplyAction="http://tempuri.org/ITeacherServices/GetTeachersPaymentFullResponse")]
        System.Data.DataSet GetTeachersPaymentFull();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/GetTeacherLastId", ReplyAction="http://tempuri.org/ITeacherServices/GetTeacherLastIdResponse")]
        int GetTeacherLastId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/GetTeacherAllPaymentReport", ReplyAction="http://tempuri.org/ITeacherServices/GetTeacherAllPaymentReportResponse")]
        System.Data.DataSet GetTeacherAllPaymentReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/GetTeacherMonthYearpaymentReport", ReplyAction="http://tempuri.org/ITeacherServices/GetTeacherMonthYearpaymentReportResponse")]
        System.Data.DataSet GetTeacherMonthYearpaymentReport(InstituteAdminSide.InstituteService.Teacher teacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherServices/DeleteTeacher", ReplyAction="http://tempuri.org/ITeacherServices/DeleteTeacherResponse")]
        int DeleteTeacher(int teacherId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeacherServicesChannel : InstituteAdminSide.InstituteService.ITeacherServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeacherServicesClient : System.ServiceModel.ClientBase<InstituteAdminSide.InstituteService.ITeacherServices>, InstituteAdminSide.InstituteService.ITeacherServices {
        
        public TeacherServicesClient() {
        }
        
        public TeacherServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeacherServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveTeacher(InstituteAdminSide.InstituteService.Teacher teacher) {
            return base.Channel.SaveTeacher(teacher);
        }
        
        public InstituteAdminSide.InstituteService.Teacher SearchTeacherData(int teacherId) {
            return base.Channel.SearchTeacherData(teacherId);
        }
        
        public int UpdateTeacher(InstituteAdminSide.InstituteService.Teacher teacher) {
            return base.Channel.UpdateTeacher(teacher);
        }
        
        public int SaveTeacherPayment(InstituteAdminSide.InstituteService.Teacher teacher) {
            return base.Channel.SaveTeacherPayment(teacher);
        }
        
        public System.Data.DataSet GetTeacherData() {
            return base.Channel.GetTeacherData();
        }
        
        public System.Data.DataSet GetTeachersIncome(InstituteAdminSide.InstituteService.Teacher teacher) {
            return base.Channel.GetTeachersIncome(teacher);
        }
        
        public System.Data.DataSet GetTeachersPaymentFull() {
            return base.Channel.GetTeachersPaymentFull();
        }
        
        public int GetTeacherLastId() {
            return base.Channel.GetTeacherLastId();
        }
        
        public System.Data.DataSet GetTeacherAllPaymentReport() {
            return base.Channel.GetTeacherAllPaymentReport();
        }
        
        public System.Data.DataSet GetTeacherMonthYearpaymentReport(InstituteAdminSide.InstituteService.Teacher teacher) {
            return base.Channel.GetTeacherMonthYearpaymentReport(teacher);
        }
        
        public int DeleteTeacher(int teacherId) {
            return base.Channel.DeleteTeacher(teacherId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstituteService.ICourseServices")]
    public interface ICourseServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseServices/SaveCourse", ReplyAction="http://tempuri.org/ICourseServices/SaveCourseResponse")]
        int SaveCourse(InstituteAdminSide.InstituteService.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseServices/UpdateCourse", ReplyAction="http://tempuri.org/ICourseServices/UpdateCourseResponse")]
        int UpdateCourse(InstituteAdminSide.InstituteService.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseServices/GetCourseData", ReplyAction="http://tempuri.org/ICourseServices/GetCourseDataResponse")]
        System.Data.DataSet GetCourseData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseServices/GetCourseLastId", ReplyAction="http://tempuri.org/ICourseServices/GetCourseLastIdResponse")]
        int GetCourseLastId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseServices/GetAllCourseData", ReplyAction="http://tempuri.org/ICourseServices/GetAllCourseDataResponse")]
        System.Data.DataSet GetAllCourseData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseServices/SearchCourse", ReplyAction="http://tempuri.org/ICourseServices/SearchCourseResponse")]
        InstituteAdminSide.InstituteService.Course SearchCourse(int courseid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseServicesChannel : InstituteAdminSide.InstituteService.ICourseServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseServicesClient : System.ServiceModel.ClientBase<InstituteAdminSide.InstituteService.ICourseServices>, InstituteAdminSide.InstituteService.ICourseServices {
        
        public CourseServicesClient() {
        }
        
        public CourseServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveCourse(InstituteAdminSide.InstituteService.Course course) {
            return base.Channel.SaveCourse(course);
        }
        
        public int UpdateCourse(InstituteAdminSide.InstituteService.Course course) {
            return base.Channel.UpdateCourse(course);
        }
        
        public System.Data.DataSet GetCourseData() {
            return base.Channel.GetCourseData();
        }
        
        public int GetCourseLastId() {
            return base.Channel.GetCourseLastId();
        }
        
        public System.Data.DataSet GetAllCourseData() {
            return base.Channel.GetAllCourseData();
        }
        
        public InstituteAdminSide.InstituteService.Course SearchCourse(int courseid) {
            return base.Channel.SearchCourse(courseid);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstituteService.IStudentServices")]
    public interface IStudentServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/SaveStudent", ReplyAction="http://tempuri.org/IStudentServices/SaveStudentResponse")]
        int SaveStudent(InstituteAdminSide.InstituteService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/UpdateStudent", ReplyAction="http://tempuri.org/IStudentServices/UpdateStudentResponse")]
        int UpdateStudent(InstituteAdminSide.InstituteService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/SearchStudentDate", ReplyAction="http://tempuri.org/IStudentServices/SearchStudentDateResponse")]
        InstituteAdminSide.InstituteService.Student SearchStudentDate(int studentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/studentlastid", ReplyAction="http://tempuri.org/IStudentServices/studentlastidResponse")]
        int studentlastid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/GetStuCourseData", ReplyAction="http://tempuri.org/IStudentServices/GetStuCourseDataResponse")]
        System.Data.DataSet GetStuCourseData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/GetAllStudentData", ReplyAction="http://tempuri.org/IStudentServices/GetAllStudentDataResponse")]
        System.Data.DataSet GetAllStudentData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/StudentClassSave", ReplyAction="http://tempuri.org/IStudentServices/StudentClassSaveResponse")]
        int StudentClassSave(InstituteAdminSide.InstituteService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/StudentAttenSave", ReplyAction="http://tempuri.org/IStudentServices/StudentAttenSaveResponse")]
        int StudentAttenSave(InstituteAdminSide.InstituteService.Student student, int month, int day, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/stupaymentcheck", ReplyAction="http://tempuri.org/IStudentServices/stupaymentcheckResponse")]
        string stupaymentcheck(int stuid, int classid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/StudentPaySave", ReplyAction="http://tempuri.org/IStudentServices/StudentPaySaveResponse")]
        int StudentPaySave(InstituteAdminSide.InstituteService.Student student, string month, int year, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/GetStudentIncomeReport", ReplyAction="http://tempuri.org/IStudentServices/GetStudentIncomeReportResponse")]
        System.Data.DataSet GetStudentIncomeReport(InstituteAdminSide.InstituteService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/GetStudentPaymentReport", ReplyAction="http://tempuri.org/IStudentServices/GetStudentPaymentReportResponse")]
        System.Data.DataSet GetStudentPaymentReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentServices/GetStudentYearpaymentReport", ReplyAction="http://tempuri.org/IStudentServices/GetStudentYearpaymentReportResponse")]
        System.Data.DataSet GetStudentYearpaymentReport(InstituteAdminSide.InstituteService.Student student);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServicesChannel : InstituteAdminSide.InstituteService.IStudentServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServicesClient : System.ServiceModel.ClientBase<InstituteAdminSide.InstituteService.IStudentServices>, InstituteAdminSide.InstituteService.IStudentServices {
        
        public StudentServicesClient() {
        }
        
        public StudentServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveStudent(InstituteAdminSide.InstituteService.Student student) {
            return base.Channel.SaveStudent(student);
        }
        
        public int UpdateStudent(InstituteAdminSide.InstituteService.Student student) {
            return base.Channel.UpdateStudent(student);
        }
        
        public InstituteAdminSide.InstituteService.Student SearchStudentDate(int studentid) {
            return base.Channel.SearchStudentDate(studentid);
        }
        
        public int studentlastid() {
            return base.Channel.studentlastid();
        }
        
        public System.Data.DataSet GetStuCourseData() {
            return base.Channel.GetStuCourseData();
        }
        
        public System.Data.DataSet GetAllStudentData() {
            return base.Channel.GetAllStudentData();
        }
        
        public int StudentClassSave(InstituteAdminSide.InstituteService.Student student) {
            return base.Channel.StudentClassSave(student);
        }
        
        public int StudentAttenSave(InstituteAdminSide.InstituteService.Student student, int month, int day, int year) {
            return base.Channel.StudentAttenSave(student, month, day, year);
        }
        
        public string stupaymentcheck(int stuid, int classid) {
            return base.Channel.stupaymentcheck(stuid, classid);
        }
        
        public int StudentPaySave(InstituteAdminSide.InstituteService.Student student, string month, int year, int amount) {
            return base.Channel.StudentPaySave(student, month, year, amount);
        }
        
        public System.Data.DataSet GetStudentIncomeReport(InstituteAdminSide.InstituteService.Student student) {
            return base.Channel.GetStudentIncomeReport(student);
        }
        
        public System.Data.DataSet GetStudentPaymentReport() {
            return base.Channel.GetStudentPaymentReport();
        }
        
        public System.Data.DataSet GetStudentYearpaymentReport(InstituteAdminSide.InstituteService.Student student) {
            return base.Channel.GetStudentYearpaymentReport(student);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstituteService.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/CheckLogIn", ReplyAction="http://tempuri.org/IAccountService/CheckLogInResponse")]
        System.Data.DataSet CheckLogIn(InstituteAdminSide.InstituteService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/ForgetPassword", ReplyAction="http://tempuri.org/IAccountService/ForgetPasswordResponse")]
        System.Data.DataSet ForgetPassword(InstituteAdminSide.InstituteService.Account account);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : InstituteAdminSide.InstituteService.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<InstituteAdminSide.InstituteService.IAccountService>, InstituteAdminSide.InstituteService.IAccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet CheckLogIn(InstituteAdminSide.InstituteService.Account account) {
            return base.Channel.CheckLogIn(account);
        }
        
        public System.Data.DataSet ForgetPassword(InstituteAdminSide.InstituteService.Account account) {
            return base.Channel.ForgetPassword(account);
        }
    }
}
