//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;

namespace InstituteAdminSide.InstituteService {
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [Serializable()]
    public partial class Employee : object, IExtensibleDataObject, INotifyPropertyChanged {
        
        [NonSerialized()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string EmpAddressField;
        
        [OptionalField()]
        private string EmpContactField;
        
        [OptionalField()]
        private string EmpFNameField;
        
        [OptionalField()]
        private int EmpIdField;
        
        [OptionalField()]
        private string EmpLNameField;
        
        [OptionalField()]
        private string EmpNICField;
        
        [OptionalField()]
        private double EmpPayAmountField;
        
        [OptionalField()]
        private DateTime EmpPayDateField;
        
        [OptionalField()]
        private string EmpPayMonthField;
        
        [OptionalField()]
        private int EmpPayYearField;
        
        [Browsable(false)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string EmpAddress {
            get {
                return this.EmpAddressField;
            }
            set {
                if ((ReferenceEquals(this.EmpAddressField, value) != true)) {
                    this.EmpAddressField = value;
                    this.RaisePropertyChanged("EmpAddress");
                }
            }
        }
        
        [DataMember()]
        public string EmpContact {
            get {
                return this.EmpContactField;
            }
            set {
                if ((ReferenceEquals(this.EmpContactField, value) != true)) {
                    this.EmpContactField = value;
                    this.RaisePropertyChanged("EmpContact");
                }
            }
        }
        
        [DataMember()]
        public string EmpFName {
            get {
                return this.EmpFNameField;
            }
            set {
                if ((ReferenceEquals(this.EmpFNameField, value) != true)) {
                    this.EmpFNameField = value;
                    this.RaisePropertyChanged("EmpFName");
                }
            }
        }
        
        [DataMember()]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [DataMember()]
        public string EmpLName {
            get {
                return this.EmpLNameField;
            }
            set {
                if ((ReferenceEquals(this.EmpLNameField, value) != true)) {
                    this.EmpLNameField = value;
                    this.RaisePropertyChanged("EmpLName");
                }
            }
        }
        
        [DataMember()]
        public string EmpNIC {
            get {
                return this.EmpNICField;
            }
            set {
                if ((ReferenceEquals(this.EmpNICField, value) != true)) {
                    this.EmpNICField = value;
                    this.RaisePropertyChanged("EmpNIC");
                }
            }
        }
        
        [DataMember()]
        public double EmpPayAmount {
            get {
                return this.EmpPayAmountField;
            }
            set {
                if ((this.EmpPayAmountField.Equals(value) != true)) {
                    this.EmpPayAmountField = value;
                    this.RaisePropertyChanged("EmpPayAmount");
                }
            }
        }
        
        [DataMember()]
        public DateTime EmpPayDate {
            get {
                return this.EmpPayDateField;
            }
            set {
                if ((this.EmpPayDateField.Equals(value) != true)) {
                    this.EmpPayDateField = value;
                    this.RaisePropertyChanged("EmpPayDate");
                }
            }
        }
        
        [DataMember()]
        public string EmpPayMonth {
            get {
                return this.EmpPayMonthField;
            }
            set {
                if ((ReferenceEquals(this.EmpPayMonthField, value) != true)) {
                    this.EmpPayMonthField = value;
                    this.RaisePropertyChanged("EmpPayMonth");
                }
            }
        }
        
        [DataMember()]
        public int EmpPayYear {
            get {
                return this.EmpPayYearField;
            }
            set {
                if ((this.EmpPayYearField.Equals(value) != true)) {
                    this.EmpPayYearField = value;
                    this.RaisePropertyChanged("EmpPayYear");
                }
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [Serializable()]
    public partial class Teacher : object, IExtensibleDataObject, INotifyPropertyChanged {
        
        [NonSerialized()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string TeacherAddressField;
        
        [OptionalField()]
        private string TeacherContactField;
        
        [OptionalField()]
        private string TeacherFNameField;
        
        [OptionalField()]
        private int TeacherIdField;
        
        [OptionalField()]
        private string TeacherLNameField;
        
        [OptionalField()]
        private string TeacherMailField;
        
        [OptionalField()]
        private string TeacherNICField;
        
        [OptionalField()]
        private double TeacherPayAmountField;
        
        [OptionalField()]
        private string TeacherPayDateField;
        
        [OptionalField()]
        private string TeacherPayMonthField;
        
        [OptionalField()]
        private int TeacherPayYearField;
        
        [OptionalField()]
        private string TeacherSubjectField;
        
        [Browsable(false)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string TeacherAddress {
            get {
                return this.TeacherAddressField;
            }
            set {
                if ((ReferenceEquals(this.TeacherAddressField, value) != true)) {
                    this.TeacherAddressField = value;
                    this.RaisePropertyChanged("TeacherAddress");
                }
            }
        }
        
        [DataMember()]
        public string TeacherContact {
            get {
                return this.TeacherContactField;
            }
            set {
                if ((ReferenceEquals(this.TeacherContactField, value) != true)) {
                    this.TeacherContactField = value;
                    this.RaisePropertyChanged("TeacherContact");
                }
            }
        }
        
        [DataMember()]
        public string TeacherFName {
            get {
                return this.TeacherFNameField;
            }
            set {
                if ((ReferenceEquals(this.TeacherFNameField, value) != true)) {
                    this.TeacherFNameField = value;
                    this.RaisePropertyChanged("TeacherFName");
                }
            }
        }
        
        [DataMember()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [DataMember()]
        public string TeacherLName {
            get {
                return this.TeacherLNameField;
            }
            set {
                if ((ReferenceEquals(this.TeacherLNameField, value) != true)) {
                    this.TeacherLNameField = value;
                    this.RaisePropertyChanged("TeacherLName");
                }
            }
        }
        
        [DataMember()]
        public string TeacherMail {
            get {
                return this.TeacherMailField;
            }
            set {
                if ((ReferenceEquals(this.TeacherMailField, value) != true)) {
                    this.TeacherMailField = value;
                    this.RaisePropertyChanged("TeacherMail");
                }
            }
        }
        
        [DataMember()]
        public string TeacherNIC {
            get {
                return this.TeacherNICField;
            }
            set {
                if ((ReferenceEquals(this.TeacherNICField, value) != true)) {
                    this.TeacherNICField = value;
                    this.RaisePropertyChanged("TeacherNIC");
                }
            }
        }
        
        [DataMember()]
        public double TeacherPayAmount {
            get {
                return this.TeacherPayAmountField;
            }
            set {
                if ((this.TeacherPayAmountField.Equals(value) != true)) {
                    this.TeacherPayAmountField = value;
                    this.RaisePropertyChanged("TeacherPayAmount");
                }
            }
        }
        
        [DataMember()]
        public string TeacherPayDate {
            get {
                return this.TeacherPayDateField;
            }
            set {
                if ((ReferenceEquals(this.TeacherPayDateField, value) != true)) {
                    this.TeacherPayDateField = value;
                    this.RaisePropertyChanged("TeacherPayDate");
                }
            }
        }
        
        [DataMember()]
        public string TeacherPayMonth {
            get {
                return this.TeacherPayMonthField;
            }
            set {
                if ((ReferenceEquals(this.TeacherPayMonthField, value) != true)) {
                    this.TeacherPayMonthField = value;
                    this.RaisePropertyChanged("TeacherPayMonth");
                }
            }
        }
        
        [DataMember()]
        public int TeacherPayYear {
            get {
                return this.TeacherPayYearField;
            }
            set {
                if ((this.TeacherPayYearField.Equals(value) != true)) {
                    this.TeacherPayYearField = value;
                    this.RaisePropertyChanged("TeacherPayYear");
                }
            }
        }
        
        [DataMember()]
        public string TeacherSubject {
            get {
                return this.TeacherSubjectField;
            }
            set {
                if ((ReferenceEquals(this.TeacherSubjectField, value) != true)) {
                    this.TeacherSubjectField = value;
                    this.RaisePropertyChanged("TeacherSubject");
                }
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [Serializable()]
    public partial class Course : object, IExtensibleDataObject, INotifyPropertyChanged {
        
        [NonSerialized()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private int CourseBatchField;
        
        [OptionalField()]
        private string CourseDayField;
        
        [OptionalField()]
        private string CourseEndTimeField;
        
        [OptionalField()]
        private int CourseIdField;
        
        [OptionalField()]
        private string CourseStartTimeField;
        
        [OptionalField()]
        private int CourseTeacherIdField;
        
        [Browsable(false)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public int CourseBatch {
            get {
                return this.CourseBatchField;
            }
            set {
                if ((this.CourseBatchField.Equals(value) != true)) {
                    this.CourseBatchField = value;
                    this.RaisePropertyChanged("CourseBatch");
                }
            }
        }
        
        [DataMember()]
        public string CourseDay {
            get {
                return this.CourseDayField;
            }
            set {
                if ((ReferenceEquals(this.CourseDayField, value) != true)) {
                    this.CourseDayField = value;
                    this.RaisePropertyChanged("CourseDay");
                }
            }
        }
        
        [DataMember()]
        public string CourseEndTime {
            get {
                return this.CourseEndTimeField;
            }
            set {
                if ((ReferenceEquals(this.CourseEndTimeField, value) != true)) {
                    this.CourseEndTimeField = value;
                    this.RaisePropertyChanged("CourseEndTime");
                }
            }
        }
        
        [DataMember()]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [DataMember()]
        public string CourseStartTime {
            get {
                return this.CourseStartTimeField;
            }
            set {
                if ((ReferenceEquals(this.CourseStartTimeField, value) != true)) {
                    this.CourseStartTimeField = value;
                    this.RaisePropertyChanged("CourseStartTime");
                }
            }
        }
        
        [DataMember()]
        public int CourseTeacherId {
            get {
                return this.CourseTeacherIdField;
            }
            set {
                if ((this.CourseTeacherIdField.Equals(value) != true)) {
                    this.CourseTeacherIdField = value;
                    this.RaisePropertyChanged("CourseTeacherId");
                }
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/InstituteServices")]
    [Serializable()]
    public partial class Student : object, IExtensibleDataObject, INotifyPropertyChanged {
        
        [NonSerialized()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string stuAddrField;
        
        [OptionalField()]
        private int stuContactField;
        
        [OptionalField()]
        private int stuCourseIDField;
        
        [OptionalField()]
        private string stuFNameField;
        
        [OptionalField()]
        private string stuGenderField;
        
        [OptionalField()]
        private string stuLNameField;
        
        [OptionalField()]
        private string stuPhotoField;
        
        [OptionalField()]
        private int stuidField;
        
        [Browsable(false)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string stuAddr {
            get {
                return this.stuAddrField;
            }
            set {
                if ((ReferenceEquals(this.stuAddrField, value) != true)) {
                    this.stuAddrField = value;
                    this.RaisePropertyChanged("stuAddr");
                }
            }
        }
        
        [DataMember()]
        public int stuContact {
            get {
                return this.stuContactField;
            }
            set {
                if ((this.stuContactField.Equals(value) != true)) {
                    this.stuContactField = value;
                    this.RaisePropertyChanged("stuContact");
                }
            }
        }
        
        [DataMember()]
        public int stuCourseID {
            get {
                return this.stuCourseIDField;
            }
            set {
                if ((this.stuCourseIDField.Equals(value) != true)) {
                    this.stuCourseIDField = value;
                    this.RaisePropertyChanged("stuCourseID");
                }
            }
        }
        
        [DataMember()]
        public string stuFName {
            get {
                return this.stuFNameField;
            }
            set {
                if ((ReferenceEquals(this.stuFNameField, value) != true)) {
                    this.stuFNameField = value;
                    this.RaisePropertyChanged("stuFName");
                }
            }
        }
        
        [DataMember()]
        public string stuGender {
            get {
                return this.stuGenderField;
            }
            set {
                if ((ReferenceEquals(this.stuGenderField, value) != true)) {
                    this.stuGenderField = value;
                    this.RaisePropertyChanged("stuGender");
                }
            }
        }
        
        [DataMember()]
        public string stuLName {
            get {
                return this.stuLNameField;
            }
            set {
                if ((ReferenceEquals(this.stuLNameField, value) != true)) {
                    this.stuLNameField = value;
                    this.RaisePropertyChanged("stuLName");
                }
            }
        }
        
        [DataMember()]
        public string stuPhoto {
            get {
                return this.stuPhotoField;
            }
            set {
                if ((ReferenceEquals(this.stuPhotoField, value) != true)) {
                    this.stuPhotoField = value;
                    this.RaisePropertyChanged("stuPhoto");
                }
            }
        }
        
        [DataMember()]
        public int stuid {
            get {
                return this.stuidField;
            }
            set {
                if ((this.stuidField.Equals(value) != true)) {
                    this.stuidField = value;
                    this.RaisePropertyChanged("stuid");
                }
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="InstituteService.IInstituteServices")]
    public interface IInstituteServices {
        
        [OperationContract(Action="http://tempuri.org/IInstituteServices/DoWork", ReplyAction="http://tempuri.org/IInstituteServices/DoWorkResponse")]
        void DoWork();
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IInstituteServicesChannel : IInstituteServices, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class InstituteServicesClient : ClientBase<IInstituteServices>, IInstituteServices {
        
        public InstituteServicesClient() {
        }
        
        public InstituteServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InstituteServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstituteServicesClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstituteServicesClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="InstituteService.IEmployeeServices")]
    public interface IEmployeeServices {
        
        [OperationContract(Action="http://tempuri.org/IEmployeeServices/SaveEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/SaveEmployeeResponse")]
        int SaveEmployee(Employee employee);
        
        [OperationContract(Action="http://tempuri.org/IEmployeeServices/SearchEmployeeData", ReplyAction="http://tempuri.org/IEmployeeServices/SearchEmployeeDataResponse")]
        Employee SearchEmployeeData(int employeeid);
        
        [OperationContract(Action="http://tempuri.org/IEmployeeServices/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeServices/UpdateEmployeeResponse")]
        int UpdateEmployee(Employee employee);
        
        [OperationContract(Action="http://tempuri.org/IEmployeeServices/SaveEmployeePayments", ReplyAction="http://tempuri.org/IEmployeeServices/SaveEmployeePaymentsResponse")]
        int SaveEmployeePayments(Employee employee);
        
        [OperationContract(Action="http://tempuri.org/IEmployeeServices/GetEmployeeData", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeeDataResponse")]
        DataSet GetEmployeeData();
        
        [OperationContract(Action="http://tempuri.org/IEmployeeServices/GetEmployeePaymentFull", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeePaymentFullResponse")]
        DataSet GetEmployeePaymentFull();
        
        [OperationContract(Action="http://tempuri.org/IEmployeeServices/GetEmployeePayment", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeePaymentResponse")]
        DataSet GetEmployeePayment();
        
        [OperationContract(Action="http://tempuri.org/IEmployeeServices/GetEmployeeLastId", ReplyAction="http://tempuri.org/IEmployeeServices/GetEmployeeLastIdResponse")]
        int GetEmployeeLastId();
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServicesChannel : IEmployeeServices, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServicesClient : ClientBase<IEmployeeServices>, IEmployeeServices {
        
        public EmployeeServicesClient() {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServicesClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveEmployee(Employee employee) {
            return base.Channel.SaveEmployee(employee);
        }
        
        public Employee SearchEmployeeData(int employeeid) {
            return base.Channel.SearchEmployeeData(employeeid);
        }
        
        public int UpdateEmployee(Employee employee) {
            return base.Channel.UpdateEmployee(employee);
        }
        
        public int SaveEmployeePayments(Employee employee) {
            return base.Channel.SaveEmployeePayments(employee);
        }
        
        public DataSet GetEmployeeData() {
            return base.Channel.GetEmployeeData();
        }
        
        public DataSet GetEmployeePaymentFull() {
            return base.Channel.GetEmployeePaymentFull();
        }
        
        public DataSet GetEmployeePayment() {
            return base.Channel.GetEmployeePayment();
        }
        
        public int GetEmployeeLastId() {
            return base.Channel.GetEmployeeLastId();
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="InstituteService.ITeacherServices")]
    public interface ITeacherServices {
        
        [OperationContract(Action="http://tempuri.org/ITeacherServices/SaveTeacher", ReplyAction="http://tempuri.org/ITeacherServices/SaveTeacherResponse")]
        int SaveTeacher(Teacher teacher);
        
        [OperationContract(Action="http://tempuri.org/ITeacherServices/SearchTeacherData", ReplyAction="http://tempuri.org/ITeacherServices/SearchTeacherDataResponse")]
        Teacher SearchTeacherData(int teacherId);
        
        [OperationContract(Action="http://tempuri.org/ITeacherServices/UpdateTeacher", ReplyAction="http://tempuri.org/ITeacherServices/UpdateTeacherResponse")]
        int UpdateTeacher(Teacher teacher);
        
        [OperationContract(Action="http://tempuri.org/ITeacherServices/SaveTeacherPayment", ReplyAction="http://tempuri.org/ITeacherServices/SaveTeacherPaymentResponse")]
        int SaveTeacherPayment(Teacher teacher);
        
        [OperationContract(Action="http://tempuri.org/ITeacherServices/GetTeacherData", ReplyAction="http://tempuri.org/ITeacherServices/GetTeacherDataResponse")]
        DataSet GetTeacherData();
        
        [OperationContract(Action="http://tempuri.org/ITeacherServices/GetTeachersIncome", ReplyAction="http://tempuri.org/ITeacherServices/GetTeachersIncomeResponse")]
        DataSet GetTeachersIncome();
        
        [OperationContract(Action="http://tempuri.org/ITeacherServices/GetTeachersPaymentFull", ReplyAction="http://tempuri.org/ITeacherServices/GetTeachersPaymentFullResponse")]
        DataSet GetTeachersPaymentFull();
        
        [OperationContract(Action="http://tempuri.org/ITeacherServices/GetTeacherLastId", ReplyAction="http://tempuri.org/ITeacherServices/GetTeacherLastIdResponse")]
        int GetTeacherLastId();
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface ITeacherServicesChannel : ITeacherServices, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class TeacherServicesClient : ClientBase<ITeacherServices>, ITeacherServices {
        
        public TeacherServicesClient() {
        }
        
        public TeacherServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeacherServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServicesClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServicesClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveTeacher(Teacher teacher) {
            return base.Channel.SaveTeacher(teacher);
        }
        
        public Teacher SearchTeacherData(int teacherId) {
            return base.Channel.SearchTeacherData(teacherId);
        }
        
        public int UpdateTeacher(Teacher teacher) {
            return base.Channel.UpdateTeacher(teacher);
        }
        
        public int SaveTeacherPayment(Teacher teacher) {
            return base.Channel.SaveTeacherPayment(teacher);
        }
        
        public DataSet GetTeacherData() {
            return base.Channel.GetTeacherData();
        }
        
        public DataSet GetTeachersIncome() {
            return base.Channel.GetTeachersIncome();
        }
        
        public DataSet GetTeachersPaymentFull() {
            return base.Channel.GetTeachersPaymentFull();
        }
        
        public int GetTeacherLastId() {
            return base.Channel.GetTeacherLastId();
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="InstituteService.ICourseServices")]
    public interface ICourseServices {
        
        [OperationContract(Action="http://tempuri.org/ICourseServices/SaveCourse", ReplyAction="http://tempuri.org/ICourseServices/SaveCourseResponse")]
        int SaveCourse(Course course);
        
        [OperationContract(Action="http://tempuri.org/ICourseServices/UpdateCourse", ReplyAction="http://tempuri.org/ICourseServices/UpdateCourseResponse")]
        int UpdateCourse(Course course);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface ICourseServicesChannel : ICourseServices, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class CourseServicesClient : ClientBase<ICourseServices>, ICourseServices {
        
        public CourseServicesClient() {
        }
        
        public CourseServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServicesClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServicesClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveCourse(Course course) {
            return base.Channel.SaveCourse(course);
        }
        
        public int UpdateCourse(Course course) {
            return base.Channel.UpdateCourse(course);
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="InstituteService.IStudentServices")]
    public interface IStudentServices {
        
        [OperationContract(Action="http://tempuri.org/IStudentServices/SaveStudent", ReplyAction="http://tempuri.org/IStudentServices/SaveStudentResponse")]
        int SaveStudent(Student student);
        
        [OperationContract(Action="http://tempuri.org/IStudentServices/UpdateStudent", ReplyAction="http://tempuri.org/IStudentServices/UpdateStudentResponse")]
        int UpdateStudent(Student student);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServicesChannel : IStudentServices, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServicesClient : ClientBase<IStudentServices>, IStudentServices {
        
        public StudentServicesClient() {
        }
        
        public StudentServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServicesClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServicesClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveStudent(Student student) {
            return base.Channel.SaveStudent(student);
        }
        
        public int UpdateStudent(Student student) {
            return base.Channel.UpdateStudent(student);
        }
    }
}
